export { default as boldItalic } from "../fonts-prebuilt/bold-italic.json";
export { default as bold } from "../fonts-prebuilt/bold.json";
export const doubleStruck = {};
export const frakturBold = {};
export const fraktur = {};
export { default as italic } from "../fonts-prebuilt/italic.json";
export { default as largeop } from "../fonts-prebuilt/largeop.json";
export const monospace = {};
export { default as normal } from "../fonts-prebuilt/normal.json";
export const sansSerifBoldItalic = {};
export const sansSerifBold = {};
export const sansSerifItalic = {};
export const sansSerif = {};
export const scriptBold = {};
export const script = {};
export { default as smallop } from "../fonts-prebuilt/smallop.json";
export const texCalligraphicBold = {};
export const texCalligraphic = {};
export const texMathit = {};
export const texOldstyleBold = {};
export const texOldstyle = {};
export { default as texSize3 } from "../fonts-prebuilt/tex-size3.json";
export { default as texSize4 } from "../fonts-prebuilt/tex-size4.json";
export const texVariant = {};
